MAT_DENSITY = 1.25  #g/cm^3 (material density), for information only
MODEL = True        #Generates model with infill
SUPPORT = True      #Generates support structure
SEPARATE_SUPPORTS = True #Spits out two files, one for the support and one for the object
PERFORATE = True    #Perforates the support structure to allow fluids into the support cells
IMG_STACK = False   #Outputs an image stack of the model
AESTHETIC = False   #Removes all internal detail, works best wtih INVERSE
INVERSE = False     #Also includes the inverse of the model as a separate file
RESOLUTION = 150    #Sets the resolution of the Y and Z axes
MODEL_THRESH = 0.1  #Influences the number of cells in the model, larger values lead to more cells
MODEL_SHELL = 3     #Sets the thickness of the model skin (in voxels), set to 0 for aesthetic models
MODEL_CELL = .7     #Sets the thickness of the cell walls within the model (in voxels)
SUPPORT_THRESH = 0.2#Influences the number of cells in the supports, larger values lead to more cells
SUPPORT_CELL = .7   #Sets the thickness of the cell walls within the supports (in voxels)
FILE_NAME = "E.stl"
#FILE_NAME = "3DBenchy_up.stl"
#FILE_NAME = "3DBenchy.stl"
#FILE_NAME = "bust_low.stl"
#FILE_NAME = "wavySurface.stl"
PRIMITIVE = False   #Set to true if you would prefer a simple geometric object, then uncomment the one you want
PRIMITIVE_TYPE = "Heart"
#PRIMITIVE_TYPE = "Cube"
#PRIMITIVE_TYPE = "Sphere"
#PRIMITIVE_TYPE = "Cylinder"
#PRIMITIVE_TYPE = "Silo"